package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoricoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoAllPropertiesEquals(Historico expected, Historico actual) {
        assertHistoricoAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoricoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoAllUpdatablePropertiesEquals(Historico expected, Historico actual) {
        assertHistoricoUpdatableFieldsEquals(expected, actual);
        assertHistoricoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoAutoGeneratedPropertiesEquals(Historico expected, Historico actual) {
        assertThat(expected)
            .as("Verify Historico auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoUpdatableFieldsEquals(Historico expected, Historico actual) {
        assertThat(expected)
            .as("Verify Historico relevant properties")
            .satisfies(e -> assertThat(e.getFechaEmision()).as("check fechaEmision").isEqualTo(actual.getFechaEmision()))
            .satisfies(e -> assertThat(e.getFolio()).as("check folio").isEqualTo(actual.getFolio()))
            .satisfies(e -> assertThat(e.getPacienteId()).as("check pacienteId").isEqualTo(actual.getPacienteId()))
            .satisfies(e -> assertThat(e.getPacienteNombre()).as("check pacienteNombre").isEqualTo(actual.getPacienteNombre()))
            .satisfies(e -> assertThat(e.getPacienteCurp()).as("check pacienteCurp").isEqualTo(actual.getPacienteCurp()))
            .satisfies(e -> assertThat(e.getMedicoId()).as("check medicoId").isEqualTo(actual.getMedicoId()))
            .satisfies(e -> assertThat(e.getMedicoNombre()).as("check medicoNombre").isEqualTo(actual.getMedicoNombre()))
            .satisfies(e -> assertThat(e.getMedicoEspecialidad()).as("check medicoEspecialidad").isEqualTo(actual.getMedicoEspecialidad()))
            .satisfies(e -> assertThat(e.getUsuarioQueRegistro()).as("check usuarioQueRegistro").isEqualTo(actual.getUsuarioQueRegistro()))
            .satisfies(e -> assertThat(e.getMedicamentos()).as("check medicamentos").isEqualTo(actual.getMedicamentos()))
            .satisfies(e -> assertThat(e.getAutorizo()).as("check autorizo").isEqualTo(actual.getAutorizo()))
            .satisfies(e -> assertThat(e.getObservaciones()).as("check observaciones").isEqualTo(actual.getObservaciones()))
            .satisfies(e -> assertThat(e.getCantidad()).as("check cantidad").isEqualTo(actual.getCantidad()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoUpdatableRelationshipsEquals(Historico expected, Historico actual) {
        // empty method
    }
}
