configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODFhZGFiNjZlMzRlZjU3YTI2YTQ1YWY4MjFmZTkwZGQxNWY3NmVjNDYwMTM2NGJlY2QzMjE4YTE0ZjM1MzA0ZjA2ODJhM2RhMWQ5MzcwYjEyOWU2M2M5NDg2MTE4MDBkMDJmM2ZiZjJmOTZkY2U4NDE2OWI3YTRjZjE4MDFiNWQ=
