package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InventarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioAllPropertiesEquals(Inventario expected, Inventario actual) {
        assertInventarioAutoGeneratedPropertiesEquals(expected, actual);
        assertInventarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioAllUpdatablePropertiesEquals(Inventario expected, Inventario actual) {
        assertInventarioUpdatableFieldsEquals(expected, actual);
        assertInventarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioAutoGeneratedPropertiesEquals(Inventario expected, Inventario actual) {
        assertThat(expected)
            .as("Verify Inventario auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioUpdatableFieldsEquals(Inventario expected, Inventario actual) {
        assertThat(expected)
            .as("Verify Inventario relevant properties")
            .satisfies(e -> assertThat(e.getClaveMedicamento()).as("check claveMedicamento").isEqualTo(actual.getClaveMedicamento()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getPresentacion()).as("check presentacion").isEqualTo(actual.getPresentacion()))
            .satisfies(e -> assertThat(e.getLote()).as("check lote").isEqualTo(actual.getLote()))
            .satisfies(e -> assertThat(e.getCantidad()).as("check cantidad").isEqualTo(actual.getCantidad()))
            .satisfies(e -> assertThat(e.getCantidadMinima()).as("check cantidadMinima").isEqualTo(actual.getCantidadMinima()))
            .satisfies(e -> assertThat(e.getFechaCaducidad()).as("check fechaCaducidad").isEqualTo(actual.getFechaCaducidad()))
            .satisfies(e -> assertThat(e.getUbicacion()).as("check ubicacion").isEqualTo(actual.getUbicacion()))
            .satisfies(e -> assertThat(e.getControlado()).as("check controlado").isEqualTo(actual.getControlado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioUpdatableRelationshipsEquals(Inventario expected, Inventario actual) {
        // empty method
    }
}
