package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MovimientoInventarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoInventarioAllPropertiesEquals(MovimientoInventario expected, MovimientoInventario actual) {
        assertMovimientoInventarioAutoGeneratedPropertiesEquals(expected, actual);
        assertMovimientoInventarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoInventarioAllUpdatablePropertiesEquals(MovimientoInventario expected, MovimientoInventario actual) {
        assertMovimientoInventarioUpdatableFieldsEquals(expected, actual);
        assertMovimientoInventarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoInventarioAutoGeneratedPropertiesEquals(MovimientoInventario expected, MovimientoInventario actual) {
        assertThat(expected)
            .as("Verify MovimientoInventario auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoInventarioUpdatableFieldsEquals(MovimientoInventario expected, MovimientoInventario actual) {
        assertThat(expected)
            .as("Verify MovimientoInventario relevant properties")
            .satisfies(e -> assertThat(e.getTipoMovimiento()).as("check tipoMovimiento").isEqualTo(actual.getTipoMovimiento()))
            .satisfies(e -> assertThat(e.getCantidad()).as("check cantidad").isEqualTo(actual.getCantidad()))
            .satisfies(e -> assertThat(e.getFecha()).as("check fecha").isEqualTo(actual.getFecha()))
            .satisfies(e -> assertThat(e.getObservacion()).as("check observacion").isEqualTo(actual.getObservacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoInventarioUpdatableRelationshipsEquals(MovimientoInventario expected, MovimientoInventario actual) {
        assertThat(expected)
            .as("Verify MovimientoInventario relationships")
            .satisfies(e -> assertThat(e.getInventario()).as("check inventario").isEqualTo(actual.getInventario()));
    }
}
