configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTUzN2MyY2E0Njc4ZjkxOThjNTNjMWI1OWVlNGJhNTFjOWQ2MDRiYjhiNGM1N2M1YTI0ZWU0NTg5NjlkZWNhNmJkNWJmZWViZTlmYjA3YjkyOGQ0ZjNkODYyYjNiMjMwYzk4ZjViMmM0ZWRjODcwNzdhNzhiZTQ4YWY4OGM4YzA=
